import mongoose from 'mongoose';
import Controller from '../../src/controllers/conversationIntelligence.js';
import Db from '../../src/db/db.js';
import Intelligence from '../../src/models/conversationIntelligence.js';
import Service from '../../src/services/conversationIntelligence.service.js';
import * as Persistence from '../../src/services/conversationIntelligence.persistence.js';
import * as Valuation from '../../src/services/valuation/opportunityValuation.service.js';
import Socket from '../../src/services/socket.service.js';
jest.mock('../../src/db/db.js',()=>({__esModule:true,default:{getBusinessByOwner:jest.fn(),getConversationById:jest.fn(),getLeadById:jest.fn(),getMessagesForAI:jest.fn()}}));
jest.mock('../../src/services/conversationIntelligence.service.js',()=>({__esModule:true,default:{analyze:jest.fn()}}));
jest.mock('../../src/services/conversationIntelligence.persistence.js',()=>({...jest.requireActual('../../src/services/conversationIntelligence.persistence.js'),claimAnalysis:jest.fn(),updateAnalyzedLead:jest.fn()}));
jest.mock('../../src/services/valuation/opportunityValuation.service.js',()=>({beginValuation:jest.fn(),finishValuation:jest.fn()}));
jest.mock('../../src/services/socket.service.js',()=>({__esModule:true,default:{emitToBusiness:jest.fn(),emitDashboardRefresh:jest.fn()}}));
let business,conversation,lead,req,res,write,analysis;
beforeEach(()=>{
 jest.clearAllMocks();jest.spyOn(console,'error').mockImplementation(()=>{});
 business={_id:new mongoose.Types.ObjectId()};lead={_id:new mongoose.Types.ObjectId(),urgency:'emergency',updatedAt:new Date()};conversation={_id:new mongoose.Types.ObjectId(),business,lead};
 req={user:{userId:new mongoose.Types.ObjectId()},params:{conversationId:String(conversation._id)},body:{force:true}};res={status:jest.fn().mockReturnThis(),json:jest.fn().mockReturnThis()};
 Db.getBusinessByOwner.mockResolvedValue(business);Db.getConversationById.mockResolvedValue(conversation);Db.getLeadById.mockResolvedValue(lead);Db.getMessagesForAI.mockResolvedValue([{body:'Sink repair',direction:'inbound',createdAt:new Date()}]);
 Persistence.claimAnalysis.mockResolvedValue({business:business._id,conversation:conversation._id,analysisRequestId:'token'});Persistence.updateAnalyzedLead.mockResolvedValue(null);
 analysis={summary:'Repair request',customerIntent:{category:'repair',serviceType:'Sink'},buyingLikelihood:{score:50},urgency:{level:'normal'},nextBestAction:{actionType:'call_soon',completed:false,outcome:''}};
 Service.analyze.mockResolvedValue(analysis);write=jest.spyOn(Intelligence,'findOneAndUpdate').mockResolvedValue({...analysis,status:'completed'});
});
afterEach(()=>jest.restoreAllMocks());
test('force cannot bypass active analysis claim',async()=>{Persistence.claimAnalysis.mockResolvedValue(null);await Controller.analyzeConversation(req,res);expect(res.status).toHaveBeenCalledWith(400);expect(Service.analyze).not.toHaveBeenCalled();expect(Valuation.beginValuation).not.toHaveBeenCalled();});
test('rejects other tenant before any claim or AI call',async()=>{conversation.business={_id:new mongoose.Types.ObjectId()};await Controller.analyzeConversation(req,res);expect(res.status).toHaveBeenCalledWith(401);expect(Persistence.claimAnalysis).not.toHaveBeenCalled();});
test('successful completion preserves staff fields and uses a fresh lead snapshot',async()=>{const fresh={...lead,updatedAt:new Date(Date.now()+1000)};Db.getLeadById.mockResolvedValueOnce(lead).mockResolvedValueOnce(fresh);await Controller.analyzeConversation(req,res);expect(res.status).toHaveBeenCalledWith(200);expect(Service.analyze).toHaveBeenCalledWith(expect.objectContaining({lead:fresh}));const set=write.mock.calls[0][1].$set;expect(set['nextBestAction.actionType']).toBe('call_soon');expect(set).not.toHaveProperty('nextBestAction');expect(set).not.toHaveProperty(['nextBestAction.completed']);expect(Persistence.updateAnalyzedLead).toHaveBeenCalledWith({lead:fresh,businessId:business._id,analysis});});
test('superseded result cannot update lead, valuation or sockets',async()=>{write.mockResolvedValue(null);await Controller.analyzeConversation(req,res);expect(Persistence.updateAnalyzedLead).not.toHaveBeenCalled();expect(Valuation.finishValuation).not.toHaveBeenCalled();expect(Socket.emitToBusiness).not.toHaveBeenCalled();});
test('provider failure releases only the owned processing claim',async()=>{Service.analyze.mockRejectedValue(new Error('provider failed'));await Controller.analyzeConversation(req,res);expect(res.status).toHaveBeenCalledWith(500);expect(write).toHaveBeenCalledWith(expect.objectContaining({analysisRequestId:'token',business:business._id,status:'processing'}),expect.objectContaining({status:'failed',analysisLeaseExpiresAt:null}));});
test('ancillary lead update failure does not relabel durable analysis failed',async()=>{Persistence.updateAnalyzedLead.mockRejectedValue(new Error('write unavailable'));await Controller.analyzeConversation(req,res);expect(res.status).toHaveBeenCalledWith(200);expect(write).toHaveBeenCalledTimes(1);});
