import { resolveOpportunityValue, ownerEstimate, unknownEstimate, moneyAmount, verifiedAmount } from '../../src/services/valuation/opportunityValue.js';
const service = { _id: 'svc', business: 'a', active: true, name: 'Drain cleaning', keywords: ['clogged drain'], estimatedValue: 225 };
const resolve = overrides => resolveOpportunityValue({ businessId: 'a', current: unknownEstimate(), services: [service], evidence: 'I need drain cleaning', ...overrides });
describe('Evidence-based opportunity valuation', () => {
  test('unknown and explicit zero are distinct', () => { expect(moneyAmount(null)).toBeNull(); expect(moneyAmount('')).toBeNull(); expect(moneyAmount(0)).toBe(0); expect(resolve({ evidence: 'hello' }).estimatedValue).toBeNull(); });
  test('uses tenant catalog, never arbitrary model dollars', () => { expect(resolve().estimatedValue).toBe(225); expect(resolve({ services: [{...service, business:'other'}] }).estimatedValue).toBeNull(); expect(resolve({services:[{...service,active:false}]}).estimatedValue).toBeNull(); });
  test('owner zero and cleared estimate remain protected', () => { for(const amount of [0,null,730]) expect(resolve({current:ownerEstimate(amount)}).estimatedValue).toBe(amount); });
  test('legacy 1200 is preserved but excluded from supported sums', () => { const value=resolve({current:{estimatedValue:1200}}); expect(value.estimatedValue).toBe(1200); expect(value.valuation.source).toBe('legacy_unverified'); expect(verifiedAmount(value)).toBeNull(); });
  test('leak is not proof of replacement or repair', () => { const services=[{...service,name:'Water heater replacement',keywords:['water heater'],estimatedValue:2000}]; expect(resolve({services,evidence:'my water heater is leaking'}).estimatedValue).toBeNull(); expect(resolve({services,evidence:'replace my water heater'}).estimatedValue).toBe(2000); expect(resolve({services,evidence:'do not replace my water heater'}).estimatedValue).toBeNull(); });
  test('ambiguous and excluded service requests stay unknown', () => { expect(resolve({services:[service,{...service,_id:'two'}]}).estimatedValue).toBeNull(); expect(resolve({services:[{...service,excludedKeywords:['commercial']}],evidence:'commercial drain cleaning'}).estimatedValue).toBeNull(); });
  test('range is grounded; no invented 25 percent spread', () => { expect(resolve().valuation).toMatchObject({minimum:225,maximum:225}); expect(resolve({services:[{...service,estimatedValue:null,priceEstimateMin:100,priceEstimateMax:300}]})).toMatchObject({estimatedValue:200,valuation:{minimum:100,maximum:300}}); });
  test('staff-selected catalog still checks business and active',()=>{expect(resolve({evidence:'',selectedServiceId:'svc'}).estimatedValue).toBe(225);expect(resolve({selectedServiceId:'svc',services:[{...service,business:'b'}]}).estimatedValue).toBeNull();});
});
